zakupki/urls.py
from django.contrib import admin
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from core import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('contracts/', views.ContractsView.as_view(), name='contracts'),
    path('contracts/<int:pk>/', views.ContractView.as_view(), name='contract'),
    path('companies/', views.CompaniesView.as_view(), name='companies'),
    path('companies/<int:pk>/', views.CompanyView.as_view(), name='company'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('webhook/', csrf_exempt(views.WebhookView.as_view()), name='webhook'),
    path('admin/', admin.site.urls),
]

core/models.py
from django.utils import timezone
from django.db import models

from core.helpers.constants import DATE_FORMAT, STATUS_TYPES, FINANCE_SOURCE_TYPES, CHOOSE_PROVIDER_TYPES
from core.helpers.functions import dict_from_choices


class Company(models.Model):
    class Meta:
        indexes = (models.Index(fields=('inn',)),)
        verbose_name = 'Организация'
        verbose_name_plural = 'Организации'

    name = models.CharField(max_length=500)
    inn = models.CharField(max_length=12)
    verbose_name = models.CharField(max_length=100, null=True, blank=True)
    address = models.CharField(null=True, blank=True, max_length=500)
    email = models.EmailField(null=True, blank=True)
    phone = models.CharField(null=True, blank=True, max_length=40)

    def __str__(self):
        return f'{self.verbose_name or self.name}'


class Contract(models.Model):
    class Meta:
        ordering = ('publish_date',)
        indexes = (models.Index(fields=('reg_number',)),)
        verbose_name = 'Контракт'
        verbose_name_plural = 'Контракты'

    reg_number = models.CharField(unique=True, max_length=60)
    status = models.CharField(choices=STATUS_TYPES, max_length=15)
    notice_number = models.CharField(unique=True, max_length=60, null=True)
    purchase_code = models.CharField(unique=True, max_length=60, null=True)
    schedule_number = models.CharField(unique=True, max_length=60, null=True)
    choose_provider_type = models.CharField(choices=CHOOSE_PROVIDER_TYPES, max_length=18, null=True)
    choose_provider_date = models.DateField(null=True)
    publish_date = models.DateField(null=True)
    props_verification = models.CharField(max_length=1000, null=True)
    customer = models.ForeignKey(to=Company, null=True, on_delete=models.SET_NULL, related_name='customer_contract')
    provider = models.ForeignKey(to=Company, null=True, on_delete=models.SET_NULL, related_name='provider_contract')
    local_number = models.CharField(max_length=40, null=True)
    start_price = models.DecimalField(decimal_places=2, max_digits=15, null=True, blank=True)
    final_price = models.DecimalField(decimal_places=2, max_digits=15)
    start_date = models.DateField()
    end_date = models.DateField()
    finance_source = models.CharField(choices=FINANCE_SOURCE_TYPES, max_length=7, null=True, blank=True)

    def __str__(self):
        return f'Контракт {self.reg_number}, ' \
            f'Статус: {dict_from_choices(STATUS_TYPES)[self.status]}, Цена: {self.final_price}'


class Stage(models.Model):
    class Meta:
        ordering = ('-date',)
        verbose_name = 'Этап'
        verbose_name_plural = 'Этапы'

    date = models.DateField()
    props_verification = models.CharField(max_length=1000)
    payed = models.DecimalField(decimal_places=2, max_digits=15)
    mistake_information = models.CharField(max_length=1000)
    contract = models.ForeignKey(to=Contract, on_delete=models.CASCADE)

    def __str__(self):
        return f'Этап для контракта {self.contract.reg_number} от {self.date.strftime(DATE_FORMAT)}'


class Purchase(models.Model):
    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    name = models.CharField(max_length=2000)
    code = models.CharField(max_length=100, null=True)
    unit = models.CharField(max_length=100)
    cost = models.DecimalField(decimal_places=2, max_digits=15, null=True)
    quantity = models.DecimalField(decimal_places=2, max_digits=15)
    contract = models.ForeignKey(to=Contract, null=True, default=None, on_delete=models.CASCADE)
    stage = models.ForeignKey(to=Stage, null=True, default=None, on_delete=models.CASCADE)

    def __str__(self):
        contract, stage = self.contract, self.stage
        if contract:
            substring = f'Позиция контракта {contract.reg_number}'
        elif stage:
            substring = f'Поставка для контракта {stage.contract.reg_number} от {stage.date.strftime(DATE_FORMAT)}'
        else:
            # так не должно быть!
            substring = ''
        return f'{substring} {self.name} {self.quantity} {self.unit}'


class ParseLog(models.Model):
    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'

    contract_reg_number = models.CharField(max_length=300)
    start_time = models.DateTimeField(auto_now_add=True)
    end_time = models.DateTimeField(blank=True, null=True)
    duration = models.DurationField(blank=True, null=True)
    success = models.BooleanField(default=False)
    error = models.TextField(null=True, blank=True)

    def __str__(self):
        msg = f'{self.contract_reg_number}, продолжительность: {self.duration}'
        if self.error:
            msg += f'ERROR: {self.error}'
        return msg

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        {% block title %}
        {% endblock title %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    <script>
        function getUrl() {
          return window.location.href;
        };
    </script>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light main-color">
        <div class="container">
            <a class="navbar-brand" href="/">Закупки</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/contracts/">Контракты</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/companies/">Компании</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0" method="get" action="/search/">
                    <input class="form-control mr-sm-2" name="search" type="text" placeholder="Поиск..."
                           aria-label="Поиск">
                    <button class="btn my-2 my-sm-0 search-button" type="submit">Искать!</button>
                </form>
            </div>
        </div>
    </nav>
</header>
{% block content %}
{% endblock content %}
</body>
</html>

templates/company.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% load tags %}
{% block title %}
    {{ company.company.inn }}
{% endblock %}
{% block content %}
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <h4 class="contract-header">
                        <a href="/companies/{{ company.company.id }}/"> {{ company.company.name }}</a>
                    </h4>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-6">
                        <h5><b>Информация</b></h5>
                        <h6><b>ИНН</b>: {{ company.company.inn }}</h6>
                        {% if company.company.email %}
                            <h6><b>Email:</b> {{ company.company.email }}</h6>
                        {% endif %}
                        {% if company.company.address %}
                            <h6><b>Адрес: </b>{{ company.company.address }}</h6>
                        {% endif %}
                        {% if company.company.phone %}
                            <h6><b>Телефон:</b> {{ company.company.phone }}</h6>
                        {% endif %}
                    </div>
                    <div class="col-6">
                        <h5><b>Контракты</b></h5>
                        <h6><b>Выполнено контрактов за год:</b> {{ company.contracts_provider|default:"0" }}</h6>
                        {% if company.contracts_provider_sum %}
                            <h6><b>На сумму:</b> {{ company.contracts_provider_sum|floatformat:2|intcomma }} рублей
                            </h6>
                        {% endif %}
                        <h6><b>Закрыто контрактов за год:</b> {{ company.contracts_customer|default:"0" }}</h6>
                        {% if company.contracts_customer_sum %}
                            <h6><b>На сумму:</b> {{ company.contracts_customer_sum|floatformat:2|intcomma }} рублей
                            </h6>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <form method="get" action="/companies/{{ company.company.pk }}/" class="row">
                    <div class="col-3">
                        <h5>Начало контракта</h5>
                        <div class="form-group">
                            <label for="start_date_bot">Контракт начан после:</label>
                            <input type="date" class="form-control" name="start_date_bot" id="start_date_bot"
                                   value={{ form.start_date_bot|date:"c" }}>
                        </div>
                        <div class="form-group">
                            <label for="start_date_bot">Контракт начан до:</label>
                            <input type="date" class="form-control" name="start_date_top" id="start_date_top"
                                   value={{ form.start_date_top|date:"c" }}>
                        </div>
                        <h5>Конец контрака</h5>
                        <div class="form-group">
                            <label for="start_date_bot">Контракт закончится после:</label>
                            <input type="date" class="form-control" name="end_date_bot" id="end_date_bot"
                                   value={{ form.end_date_bot|date:"c" }}>
                        </div>
                        <div class="form-group">
                            <label for="start_date_bot">Контракт закончится до:</label>
                            <input type="date" class="form-control" name="end_date_top" id="end_date_top"
                                   value={{ form.end_date_top|date:"c" }}>
                        </div>
                    </div>
                    <div class="col-3">
                        <h5>Заказчик</h5>
                        <div class="form-group">
                            <label for="customer_inn">ИНН:</label>
                            <input type="text" class="form-control" name="customer_inn"
                                   id="customer_inn" value="{{ form.customer_inn }}">
                        </div>
                        <div class="form-group">
                            <label for="customer_name">Название:</label>
                            <input type="text" class="form-control" name="customer_name" id="customer_name"
                                   value="{{ form.customer_name }}">
                        </div>
                        <h5>Поставщик</h5>
                        <div class="form-group">
                            <label for="provider_inn">ИНН:</label>
                            <input type="text" class="form-control" name="provider_inn" id="provider_inn"
                                   value="{{ form.provider_inn }}">
                        </div>
                        <div class="form-group">
                            <label for="provider_name">Название:</label>
                            <input type="text" class="form-control" name="provider_name" id="provider_name"
                                   value="{{ form.provider_name }}">
                        </div>
                    </div>
                    <div class="col-6">
                        <h5>Цена контракта</h5>
                        <div class="form-group">
                            <label for="final_price_bot">Больше:</label>
                            <input type="number" class="form-control" name="final_price_bot" id="final_price_bot"
                                   value={{ form.final_price_bot }}>
                        </div>
                        <div class="form-group">
                            <label for="final_price_top">Меньше:</label>
                            <input type="number" class="form-control" name="final_price_top" id="final_price_top"
                                   value="{{ form.final_price_top }}">
                        </div>
                        <h5>Типы контрактов</h5>
                        <div class="form-group">
                            <label for="status">Статус:</label>
                            <select class="form-control" name="status" id="status">
                                <option value="">Все</option>
                                {% for status in statuses %}
                                    {% if form.status == status.value %}
                                        <option selected value="{{ status.value }}">{{ status.label }}</option>
                                    {% else %}
                                        <option value="{{ status.value }}">{{ status.label }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="provider_type">Способ выбора поставщика:</label>
                            <select class="form-control" name="provider_type" id="provider_type">
                                <option value="">Все</option>
                                {% for provider_type in provider_types %}
                                    {% if form.provider_type == provider_type.value %}
                                        <option selected
                                                value="{{ provider_type.value }}">{{ provider_type.label }}</option>
                                    {% else %}
                                        <option value="{{ provider_type.value }}">{{ provider_type.label }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="col-12 center">
                        <button type="submit" class="btn btn-lg my-2 my-sm-0 search-button float-right">Искать</button>
                    </div>
                </form>
            </div>
        </div>
        {% for contract in contract_list %}
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <h4 class="contract-header">
                            <a href="/contracts/{{ contract.id }}/">Контракт № {{ contract.reg_number }}</a>
                        </h4>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-3">
                            <h6><b>{{ contract.final_price|floatformat:2|intcomma }} рублей</b></h6>
                            <h6>{{ contract.get_status_display }}</h6>
                        </div>
                        <div class="col-5">
                            <h6> Заказчик: <a href="/companies/{{ contract.customer_id }}/">
                                {% if contract.customer.verbose_name %}
                                    {{ contract.customer.verbose_name }}
                                {% else %}
                                    {{ contract.customer.name }}
                                {% endif %}
                            </a></h6>
                            <h6> Поставщик: <a href="/companies/{{ contract.provider_id }}/">
                                {% if contract.provider.verbose_name %}
                                    {{ contract.provider.verbose_name }}
                                {% else %}
                                    {{ contract.provider.name }}
                                {% endif %}
                            </a>
                            </h6>
                        </div>
                        <div class="col-4">
                            <h6>Дата начала:<b class="float-right">{{ contract.start_date }}</b></h6>
                            <h6>Дата окончания: <b class="float-right">{{ contract.end_date }}</b></h6>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        {% if not contract_list %}
            <div class="row justify-content-center">
                <h4>Контрактов не найдено</h4>
            </div>

        {% endif %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="?{% url_replace page=page_obj.previous_page_number %}">Назад</a>
                {% endif %}
                <span class="page-current">
                    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="?{% url_replace page=page_obj.next_page_number %}">Вперед</a>
                {% endif %}
            </span>
        </div>
    </div>
{% endblock %}

templates/contracts.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load tags %}
{% load humanize %}
{% block title %}
    Контракты
{% endblock %}
{% block content %}

    <div class="container">
        <div class="card">
            <div class="card-body">
                <form method="get" action="/contracts/" class="row">
                    <div class="col-3">
                        <h5>Дата заключения</h5>
                        <div class="form-group">
                            <label for="start_date_bot">Контракт заключен после:</label>
                            <input type="date" class="form-control" name="start_date_bot" id="start_date_bot"
                                   value={{ form.start_date_bot|date:"c" }}>
                        </div>
                        <div class="form-group">
                            <label for="start_date_bot">Контракт заключен до:</label>
                            <input type="date" class="form-control" name="start_date_top" id="start_date_top"
                                   value={{ form.start_date_top|date:"c" }}>
                        </div>
                        <h5>Дата завершения</h5>
                        <div class="form-group">
                            <label for="start_date_bot">Контракт завершен после:</label>
                            <input type="date" class="form-control" name="end_date_bot" id="end_date_bot"
                                   value={{ form.end_date_bot|date:"c" }}>
                        </div>
                        <div class="form-group">
                            <label for="start_date_bot">Контракт завершен до:</label>
                            <input type="date" class="form-control" name="end_date_top" id="end_date_top"
                                   value={{ form.end_date_top|date:"c" }}>
                        </div>
                    </div>
                    <div class="col-3">
                        <h5>Заказчик</h5>
                        <div class="form-group">
                            <label for="customer_inn">ИНН:</label>
                            <input type="text" class="form-control" name="customer_inn"
                                   id="customer_inn" value="{{ form.customer_inn }}">
                        </div>
                        <div class="form-group">
                            <label for="customer_name">Название:</label>
                            <input type="text" class="form-control" name="customer_name" id="customer_name"
                                   value="{{ form.customer_name }}">
                        </div>
                        <h5>Поставщик</h5>
                        <div class="form-group">
                            <label for="provider_inn">ИНН:</label>
                            <input type="text" class="form-control" name="provider_inn" id="provider_inn"
                                   value="{{ form.provider_inn }}">
                        </div>
                        <div class="form-group">
                            <label for="provider_name">Название:</label>
                            <input type="text" class="form-control" name="provider_name" id="provider_name"
                                   value="{{ form.provider_name }}">
                        </div>
                    </div>
                    <div class="col-6">
                        <h5>Цена контракта</h5>
                        <div class="form-group">
                            <label for="final_price_bot">От:</label>
                            <input type="number" class="form-control" name="final_price_bot" id="final_price_bot"
                                   value={{ form.final_price_bot }}>
                        </div>
                        <div class="form-group">
                            <label for="final_price_top">До:</label>
                            <input type="number" class="form-control" name="final_price_top" id="final_price_top"
                                   value="{{ form.final_price_top }}">
                        </div>
                        <h5>Типы контрактов</h5>
                        <div class="form-group">
                            <label for="status">Статус:</label>
                            <select class="form-control" name="status" id="status">
                                <option value="">Все</option>
                                {% for status in statuses %}
                                    {% if form.status == status.value %}
                                        <option selected value="{{ status.value }}">{{ status.label }}</option>
                                    {% else %}
                                        <option value="{{ status.value }}">{{ status.label }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="provider_type">Способ выбора поставщика:</label>
                            <select class="form-control" name="provider_type" id="provider_type">
                                <option value="">Все</option>
                                {% for provider_type in provider_types %}
                                    {% if form.provider_type == provider_type.value %}
                                        <option selected
                                                value="{{ provider_type.value }}">{{ provider_type.label }}</option>
                                    {% else %}
                                        <option value="{{ provider_type.value }}">{{ provider_type.label }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                <div class="col-12 center">
                    <button type="submit" class="btn btn-lg my-2 my-sm-0 search-button float-right">Искать</button>
                </div>
                </form>
            </div>
        </div>
        {% for contract in contract_list %}
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <h4 class="contract-header">
                            <a href="/contracts/{{ contract.id }}/">Контракт № {{ contract.reg_number }}</a>
                        </h4>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-3">
                            <h6><b>{{ contract.final_price|floatformat:2|intcomma }} рублей</b></h6>
                            <h6>{{ contract.get_status_display }}</h6>
                        </div>
                        <div class="col-5">
                            <h6> Заказчик: <a href="/companies/{{ contract.customer_id }}/">
                                {% if contract.customer.verbose_name %}
                                    {{ contract.customer.verbose_name }}
                                {% else %}
                                    {{ contract.customer.name }}
                                {% endif %}
                            </a></h6>
                            <h6> Поставщик: <a href="/companies/{{ contract.provider_id }}/">
                                {% if contract.provider.verbose_name %}
                                    {{ contract.provider.verbose_name }}
                                {% else %}
                                    {{ contract.provider.name }}
                                {% endif %}
                            </a>
                            </h6>
                        </div>
                        <div class="col-4">
                            <h6>Дата начала:<b class="float-right">{{ contract.start_date }}</b></h6>
                            <h6>Дата окончания: <b class="float-right">{{ contract.end_date }}</b></h6>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        {% if not contract_list %}
            <div class="row justify-content-center">
                <h4>Контрактов не найдено</h4>
            </div>

        {% endif %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="?{% url_replace page=page_obj.previous_page_number %}">Назад</a>
                {% endif %}
                <span class="page-current">
                    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="?{% url_replace page=page_obj.next_page_number %}">Вперед</a>
                {% endif %}
            </span>
        </div>
    </div>
{% endblock %}

templates/error.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Ошибка
{% endblock %}
{% block content %}
    <div class="container">
        <h2>По вашему запросу ничего не найдено. <a href="/contracts/">На главную</a>.</h2>
    </div>
{% endblock %}